name: Docker Build and Push

on:
  push:
    branches:
      - 'master'
  create:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get tags
        id: gen_tags
        run: |
          echo $GITHUB_REF
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAG=${GITHUB_REF/refs\/tags\//}
          fi
          SHORT_SHA=$(echo $GITHUB_SHA | head -c7)
          echo '::set-output name=SHORT_SHA::'$SHORT_SHA
          echo '::set-output name=TAG::'$TAG
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push on tag
        if: ${{ contains(env.GITHUB_REF, 'tags') }}
        id: docker_build_tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/arpeggio:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/arpeggio:${{ steps.gen_tags.outputs.SHORT_SHA }}
            ${{ secrets.DOCKERHUB_USERNAME }}/arpeggio:${{ steps.gen_tags.outputs.TAG }}
      -
        name: Build and push on push
        if: ${{ !contains(env.GITHUB_REF, 'tags') }}
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/arpeggio:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/arpeggio:${{ steps.gen_tags.outputs.SHORT_SHA }}
